version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hr_mailer_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - ENABLE_MOCK_AUTH=false
    volumes:
      - hrmailer_db:/app/database
      - hrmailer_uploads:/app/uploads
      - hrmailer_logs:/app/logs
    env_file:
      - .env

volumes:
  hrmailer_db:
  hrmailer_uploads:
  hrmailer_logs:
